/**
 * Author: Huibin.guan
 * Date: 2018-09-29
 * Time: 23:57
 *
 */
export const SET_STUENT_REQUIREMENT = 'SET_STUENT_REQUIREMENT'

export const SET_STUDENT_MESSAGE_DETAIL = 'SET_STUDENT_MESSAGE_DETAIL'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const SET_TEACH_ADDRESS_LAT_LNG = 'SET_TEACH_ADDRESS_LAT_LNG'

export const SET_ORG_LINE_COURSE = 'SET_ORG_LINE_COURSE'

export const SET_ORG_GIFT_LIST = 'SET_ORG_GIFT_LIST'

export const SET_ORG_TEACHER = 'SET_ORG_TEACHER'

export const SET_AGREED_DETAIL = 'SET_AGREED_DETAIL'
